/*************************************************************

	LSD 9.0 - January 2024
	written by Marco Valente, Universita' dell'Aquila
	and by Marcelo Pereira, University of Campinas

	Copyright Marco Valente and Marcelo Pereira
	LSD is distributed under the GNU General Public License

	See Readme.txt for copyright information of
	third parties' code used in LSD

 *************************************************************/

/*************************************************************
 LIBMAIN.CPP
 Contains the LSD library global variables and the library
 start-up and shut-down functions.

 The main functions contained here are:

 - lsd_constructor( ), lsd_destructor( )
 Allocates and initializes the global variables on program
 startup, and destroys allocated global variables on program
 exit.
*************************************************************/

#include "decl.h"

/*********************************
 GLOBAL VARIABLES
 *********************************/
// global variables setting library defaults
char nonavail[ ] = "NA";	// string for unavailable values (use R default)
double def_res = 0;			// default equation result
int add_to_tot = false;		// flag to append results to existing totals file (bool)
int dobar = false;			// output a progress bar to the log/standard output
int docsv = false;			// produce .csv text results files (bool)
int dozip = true;			// compressed results file flag (bool)
int max_step = MAX_STEPS;	// number of simulation steps
unsigned seed = 1;			// random number generator initial seed

// regular library global variables
bool batch_sequential = false;// no-window multi configuration job running
bool error_hard_thread;		// flag to error_hard() called in worker thread
bool fast;					// safe copy of fast_mode flag
bool grandTotal = false;	// flag to produce grand total in batch processing
bool idle_loop = false;		// indicates in main idle loop (no running operation)
bool message_logged = false;// new message posted in log window
bool no_more_memory = false;// memory overflow when setting data save structure
bool no_saved = true;		// disable the usage of saved values as lagged ones
bool no_search;				// disable the standard variable search mechanism
bool no_search_up;			// disable the object up-search mechanism
bool no_zero_instance = true;// flag to allow deleting last object instance
bool on_bar;				// flag to indicate bar is being draw in log window
bool parallel_abort;		// indicate parallel threads were aborted
bool parallel_mode;			// parallel mode (multithreading) status
bool parallel_monitor;		// parallel monitor thread status
bool pause_run;				// pause running simulation
bool running = false;		// simulation is running
bool save_alt_path = false;	// alternate save path flag
bool save_ok = true;		// control if saving model configuration is possible
bool scrollB = true;		// scroll box state in current runtime plot
bool struct_loaded = false;	// a valid configuration file is loaded
bool unsavedData = false;	// flag unsaved simulation results
bool unsavedSense = false;	// control for unsaved changes in sensitivity data
bool user_exception = false;// flag indicating exception was generated by user code
bool use_nan;				// flag to allow using Not a Number value
bool watch_trigger = false;	// indicate that a watch condition was met
bool watch_write_mode;		// flag for write-only watch condition
bool worker_ready;			// parallel worker ready flag
bool worker_crashed;		// parallel worker crash flag
char *alt_path = NULL;		// alternative output path
char *eq_file = NULL;		// equation file content
char *exec_file = NULL;		// name of executable file
char *exec_path = NULL;		// path of executable file
char *log_filename = NULL;	// name of log file, if any
char *rootLsd = NULL;		// path of LSD root directory
char *path = NULL;			// path of current configuration
char *sens_file = NULL;		// current sensitivity analysis file
char *simul_name = NULL;	// name of current simulation configuration
char *struct_file = NULL;	// name of current configuration file
char equation_name[ MAX_PATH_LENGTH ] = "";// equation file name
char error_hard_msg1[ MAX_BUFF_SIZE ];	// buffer for parallel worker title msg
char error_hard_msg2[ MAX_BUFF_SIZE ];	// buffer for parallel worker log msg
char error_hard_msg3[ MAX_BUFF_SIZE ];	// buffer for parallel worker box msg
char lsd_eq_file[ MAX_FILE_SIZE ] = "";	// equations saved in configuration file
char name_rep[ MAX_PATH_LENGTH ] = "";	// documentation report file name
char path_res[ MAX_PATH_LENGTH ] = "";	// path of last used results directory
char watch_elem[ MAX_ELEM_LENGTH + 1 ] = "";// name of element triggering watch condition
description *descr = NULL;	// model description structure
dlliblinkage liblnk;		// call-back references for DLL
eq_mapT eq_map;				// fast equation look-up map
int actual_steps = 0;		// number of executed time steps
int choice;					// Tcl menu control variable (main window)
int cur_plt;				// current graph plot number
int cur_sim;				// current simulation run
int debug_flag = false;		// debug enable control (bool)
int done_in;				// Tcl menu control variable (log window)
int fast_mode;				// level of LOG messages & runtime plot
int fend;					// last multi configuration job to run
int findex;					// current multi configuration job
int findexSens = 0;			// index to sequential sensitivity configuration filenames
int log_start;				// first period to start logging to file
int log_stop;				// last period to log to file, if any
int max_runs;				// maximum number of parallel runs
int max_threads;			// maximum number of parallel threads per run
int no_ptr_chk = false;		// disable user pointer checking
int no_res = false;			// do not produce .res results files (bool)
int no_tot = true;			// do not produce .tot totals files (bool)
int parallel_disable = false;// flag to control parallel mode
int prof_aggr_time = false;	// show aggregate profiling times
int prof_min_msecs = 0;		// profile only variables taking more than X msecs.
int prof_obs_only = false;	// profile only observed variables
int quit = 0;				// simulation interruption mode (0=none)
int series_saved = 0;		// number of series saved
int sim_num = 1;			// simulation number running
int stack_level;			// LSD stack call level
int stack_info = 0;			// LSD stack control
int t;						// current time step
int when_debug;				// next debug stop time step (0 for none)
int wr_warn_cnt;			// invalid write operations warning counter
lattice latt;				// model lattice
long nodesSerial = 1;		// network node's serial number global counter
lsdstack *stack_log = NULL;	// LSD stack
map < string, profile > prof;// set of saved profiling times
object *blueprint = NULL;	// LSD blueprint (effective model in use)
object *root = NULL;		// LSD root object
object *wait_delete = NULL;	// LSD object waiting for deletion
o_setT obj_list;			// set with all existing LSD objects
sense *rsense = NULL;		// LSD sensitivity analysis structure
variable *cemetery = NULL;	// LSD saved data from deleted objects
variable *last_cemetery = NULL;// LSD last saved data from deleted objects
vector < string > res_list;	// list of results files last saved
FILE *log_file = NULL;		// log file, if any

// constant arrays
const char *desc_key_words[ DESC_KEY_NUM ] = DESC_KEY_WORDS;
const char *elem_type_names[ ELEM_TYPE_NUM ] = ELEM_TYPE_NAMES;
const char *signal_names[ REG_SIG_NUM ] = REG_SIG_NAME;
const int signals[ REG_SIG_NUM ] = REG_SIG_CODE;

// conditional variables
#ifndef _NP_
atomic < bool > parallel_ready( true );// flag to indicate variable worker is ready
map < thread::id, worker * > thr_ptr;// worker thread pointers
mutex lock_obj_list;		// lock for object list for parallel manipulation
mutex lock_run_logs;		// lock run_logs for parallel updating
mutex lock_run_pids;		// lock run_pids for parallel updating
mutex lock_run_status;		// lock run_status for parallel updating
string run_log;				// consolidated runs log
thread run_monitor;			// thread monitoring parallel instances
thread::id main_thread;		// LSD main thread ID
vector < handleT > run_pids;// parallel running instances process id's
vector < int > run_status;	// parallel running instances status
vector < string > run_logs;	// list of log files produced in parallel runs
vector < string > run_results;// parallel run results files
vector < thread > run_threads;// parallel running instances
worker *workers = NULL;		// multi-thread parallel worker data
#endif

// debugger temporary storage
#ifndef _NW_
double d_values[ USER_D_VARS ];
int i_values[ 4 ];			// user temporary variables copy
netLink *n_values[ 10 ];
object *o_values[ 10 ];
p_mapT par_map;				// variable to parent name map for AoR
FILE *f_values[ 1 ];
Tcl_Interp *inter = NULL;	// Tcl interpreter in GUI (for legacy LSD code)
#endif


/*********************************
 LIB_CONSTRUCTOR
 *********************************/
void __attribute__( ( constructor ) ) lib_constructor( )
{
	path = new char[ strlen( "" ) + 1 ];
	simul_name = new char[ strlen( "" ) + 1 ];
	strcpy( path, "" );
	strcpy( simul_name, "" );

#ifndef _NP_
	main_thread = this_thread::get_id( );
	max_threads = ( MAX_CORES <= 0 ) ? thread::hardware_concurrency( ) : MAX_CORES;
#else
	max_threads = ( MAX_CORES <= 0 ) ? 4 : MAX_CORES;
#endif

	root = new object;
	root->init( NULL, "Root" );
	add_description( "Root" );
	reset_blueprint( NULL );

	// create fast equation look-up map if required
	if ( fast_lookup )
		init_map( );

	stack_log = new lsdstack;
	stack_log->prev = NULL;
	stack_log->next = NULL;
	stack_log->ns = 0;
	stack_log->vs = NULL;
	strcpy( stack_log->label, "LSD Simulation Manager" );
	stack_level = 0;
}


/*********************************
 LIB_DESTRUCTOR
 *********************************/
void __attribute__( ( destructor ) ) lib_destructor( )
{
	empty_stack( );
	empty_lattice( );
	empty_sensitivity( NULL );
	empty_cemetery( );
	empty_blueprint( );
	empty_description( );
	root->delete_obj( );

	delete stack_log;
	delete [ ] path;
	delete [ ] rootLsd;
	delete [ ] exec_path;
	delete [ ] exec_file;
	delete [ ] simul_name;
	delete [ ] eq_file;
	delete [ ] struct_file;
	delete [ ] log_filename;
}
