#!/bin/sh

# **************************************************************
#
#	LSD 9.0 - January 2026
#	written by Marco Valente, Universita' dell'Aquila
#	and by Marcelo Pereira, University of Campinas
#
#	Copyright Marco Valente and Marcelo Pereira
#	LSD is distributed under the GNU General Public License
#
# **************************************************************

# **************************************************************
# LWI-CLEANUP
# Delete temporary files from LSD web interface
# Must be scheduled to be run periodically
# In typical Linux installations, daily runs can be set by:
#  chmod a+x lwi-cleanup
#  sudo cp lwi-cleanup /etc/cron.daily
# **************************************************************

BASE_WWW_PATH="/var/www"

find -L $BASE_WWW_PATH -type f -wholename "*/tmp/*" -mtime +2 -delete
