#**************************************************************
#
#	LSD 9.0 - January 2024
#	written by Marco Valente, Universita' dell'Aquila
#	and by Marcelo Pereira, University of Campinas
#
#	Copyright Marco Valente and Marcelo Pereira
#	LSD is distributed under the GNU General Public License
#
#**************************************************************

#**************************************************************
# MAKEFILE.CONFGEN
# Makefile for lsd_confgen
# In a command prompt (terminal) in LSD root directory, use
#  cd lwi
#  make -f makefile.confgen
#**************************************************************

CC=g++
TARGET=lsd_confgen
SWITCH_CC=-D_NW_ -D_NP_ -std=c++11 -Wno-unused-result -O3

# from here you should not need to modify anything

# add differentiating platform suffix
ifeq ($(OS),Windows_NT)
	OBJ_DIR=$(TMP)/$(TARGET)/
	EXT=.exe
	EXEC=$(TARGET)$(EXT)
else
	ifeq ($(shell uname -s),Darwin)
		OBJ_DIR=$(TMPDIR)/$(TARGET)/
		EXT=
		EXEC=$(TARGET)OSX
	else
		OBJ_DIR=$(TMPDIR)/$(TARGET)/
		EXT=
		EXEC=$(TARGET)
	endif
endif

# using GCC in the OS
LSDROOT=..
SRC=src
SRC_DIR=$(LSDROOT)/$(SRC)/
LIB_DIR=$(SRC_DIR)lib/
INCLUDE=-I$(LSDROOT)/$(SRC)
LIB=-lz
RM=@rm$(EXT) -f
MKDIR=@mkdir$(EXT) -p

# make rules
$(EXEC): $(OBJ_DIR)confgen.o $(OBJ_DIR)libmain.o $(OBJ_DIR)commonlib.o $(OBJ_DIR)description.o $(OBJ_DIR)filelib.o $(OBJ_DIR)latticelib.o $(OBJ_DIR)math.o $(OBJ_DIR)nets.o $(OBJ_DIR)object.o $(OBJ_DIR)parallel.o $(OBJ_DIR)run.o $(OBJ_DIR)stattables.o $(OBJ_DIR)utillib.o $(OBJ_DIR)variab.o $(OBJ_DIR)pugixml.o
	$(CC) $(SWITCH_CC) $(OBJ_DIR)confgen.o $(OBJ_DIR)commonlib.o $(OBJ_DIR)description.o $(OBJ_DIR)filelib.o $(OBJ_DIR)latticelib.o $(OBJ_DIR)math.o $(OBJ_DIR)nets.o $(OBJ_DIR)object.o $(OBJ_DIR)parallel.o $(OBJ_DIR)run.o $(OBJ_DIR)stattables.o $(OBJ_DIR)utillib.o $(OBJ_DIR)variab.o $(OBJ_DIR)pugixml.o $(LIB) -o $(EXEC)

# executable modules
$(OBJ_DIR)confgen.o: $(SRC_DIR)confgen.cpp $(SRC_DIR)libLSD.h
	$(MKDIR) $(@D)
	$(CC) $(SWITCH_CC_NW) $(INCLUDE) -c $(SRC_DIR)confgen.cpp -o $(OBJ_DIR)confgen.o

$(OBJ_DIR)libmain.o: $(LIB_DIR)libmain.cpp $(SRC_DIR)libLSD.h
	$(MKDIR) $(@D)
	$(CC) $(SWITCH_CC_NW) $(INCLUDE) -c $(LIB_DIR)libmain.cpp -o $(OBJ_DIR)libmain.o

$(OBJ_DIR)commonlib.o: $(LIB_DIR)commonlib.cpp $(SRC_DIR)libLSD.h
	$(MKDIR) $(@D)
	$(CC) $(SWITCH_CC_NW) $(INCLUDE) -c $(LIB_DIR)commonlib.cpp -o $(OBJ_DIR)commonlib.o

$(OBJ_DIR)description.o: $(LIB_DIR)description.cpp $(SRC_DIR)libLSD.h
	$(MKDIR) $(@D)
	$(CC) $(SWITCH_CC_NW) $(INCLUDE) -c $(LIB_DIR)description.cpp -o $(OBJ_DIR)description.o

$(OBJ_DIR)filelib.o: $(LIB_DIR)filelib.cpp $(SRC_DIR)libLSD.h
	$(MKDIR) $(@D)
	$(CC) $(SWITCH_CC_NW) $(INCLUDE) -c $(LIB_DIR)filelib.cpp -o $(OBJ_DIR)filelib.o

$(OBJ_DIR)latticelib.o: $(LIB_DIR)latticelib.cpp $(SRC_DIR)libLSD.h
	$(MKDIR) $(@D)
	$(CC) $(SWITCH_CC_NW) $(INCLUDE) -c $(LIB_DIR)latticelib.cpp -o $(OBJ_DIR)latticelib.o

$(OBJ_DIR)math.o: $(LIB_DIR)math.cpp $(SRC_DIR)libLSD.h
	$(MKDIR) $(@D)
	$(CC) $(SWITCH_CC_NW) $(INCLUDE) -c $(LIB_DIR)math.cpp -o $(OBJ_DIR)math.o

$(OBJ_DIR)nets.o: $(LIB_DIR)nets.cpp $(SRC_DIR)libLSD.h
	$(MKDIR) $(@D)
	$(CC) $(SWITCH_CC_NW) $(INCLUDE) -c $(LIB_DIR)nets.cpp -o $(OBJ_DIR)nets.o

$(OBJ_DIR)object.o: $(LIB_DIR)object.cpp $(SRC_DIR)libLSD.h
	$(MKDIR) $(@D)
	$(CC) $(SWITCH_CC_NW) $(INCLUDE) -c $(LIB_DIR)object.cpp -o $(OBJ_DIR)object.o

$(OBJ_DIR)parallel.o: $(LIB_DIR)parallel.cpp $(SRC_DIR)libLSD.h
	$(MKDIR) $(@D)
	$(CC) $(SWITCH_CC_NW) $(INCLUDE) -c $(LIB_DIR)parallel.cpp -o $(OBJ_DIR)parallel.o

$(OBJ_DIR)run.o: $(LIB_DIR)run.cpp $(SRC_DIR)libLSD.h
	$(MKDIR) $(@D)
	$(CC) $(SWITCH_CC_NW) $(INCLUDE) -c $(LIB_DIR)run.cpp -o $(OBJ_DIR)run.o

$(OBJ_DIR)stattables.o: $(LIB_DIR)stattables.cpp $(SRC_DIR)libLSD.h
	$(MKDIR) $(@D)
	$(CC) $(SWITCH_CC_NW) $(INCLUDE) -c $(LIB_DIR)stattables.cpp -o $(OBJ_DIR)stattables.o

$(OBJ_DIR)utillib.o: $(LIB_DIR)utillib.cpp $(SRC_DIR)libLSD.h
	$(MKDIR) $(@D)
	$(CC) $(SWITCH_CC_NW) $(INCLUDE) -c $(LIB_DIR)utillib.cpp -o $(OBJ_DIR)utillib.o

$(OBJ_DIR)variab.o: $(LIB_DIR)variab.cpp $(SRC_DIR)libLSD.h
	$(MKDIR) $(@D)
	$(CC) $(SWITCH_CC_NW) $(INCLUDE) -c $(LIB_DIR)variab.cpp -o $(OBJ_DIR)variab.o

$(OBJ_DIR)pugixml.o: $(SRC_DIR)pugixml/pugixml.cpp $(SRC_DIR)pugixml/pugixml.hpp $(SRC_DIR)pugixml/pugiconfig.hpp
	$(MKDIR) $(@D)
	$(CC) $(SWITCH_CC_NW) $(INCLUDE) -c $(SRC_DIR)pugixml/pugixml.cpp -o $(OBJ_DIR)pugixml.o

# remove compiled files
clean:
	$(RM) $(OBJ_DIR)* $(EXEC)
