#*******************************************************************************
#
# ---------------- Polynomial Regression-Sobol OLS DoE analysis ---------------
#
#   Written by Marcelo C. Pereira, University of Campinas
#
#   Copyright Marcelo C. Pereira
#   Distributed under the GNU General Public License
#
#   The default configuration assumes that the supplied LSD
#   main simulation configuration (basename sa-sobol):
#     R/data/sa-sobol.lsd
#   is used with the also supplied sensitivity analysis (SA) set:
#     R/data/sa-sobol.sa
#   to generate a set of configurations which must be executed
#   before this script is used
#
#   To generate the configuration set, (1) open LSD Model Manager
#   (LMM), (2) in LSD Model Browser, open the model which contains
#   this script (double click), (3) in LMM, compile and run the
#   model (menu Model>Compile and Run), (4) in LSD Model Browser,
#   load the desired configuration (menu File>Load), (5) load the
#   desired SA set (menu File>Load Sensitivity), (6) generate the
#   configuration set (menu Data>Sensitivity Analysis>NOLH Sampling),
#   accepting all the default options, (7) create an out-of-sample
#   set of samples when asked by LSD, accepting the proposed number
#   of samples.
#
#   To execute the simulation set, (8) create a parallel processing
#   batch (menu Run>Parallel Batch), accepting to use the configura-
#   tion set just created and the default options, (9) execute the
#   created batch, accepting the option offered, (10) confirm opening
#   the background run monitor, (11) wait until all simulation runs
#   in the background run monitor finish.
#
#	  Several files are required to run this script:
#	  	folder/basename.lsd                         : LSD main configuration
#	  	folder/basename.sa                          : LSD SA set
#	  	folder/basename/basename_XX_YY.csv          : DoE specification
#	  	folder/basename/basename_YY+1_ZZ.csv        : validation sample
#	  	folder/basename/basename_XX_YY_WWW.res.gz   : DoE response
#	  	folder/basename/basename_YY+1_ZZ_WWW.res.gz : validation response
#   The last four sets of files do NOT come with LSD and must be
#   generated by the steps described above before using this script.
#
#   IMPORTANT: this script assumes the R working directory is set
#   to the R subfolder where this script file is stored. This can
#   be done automatically in RStudio if a project is created at
#   this subfolder, or using the command setwd(). The "folder"
#   variable below must always point to a (relative) subfolder
#   of the R working directory.
#
#*******************************************************************************

# ====== User parameters ======

# database files / time steps to use
folder    <- "data"                 # data files folder
baseName  <- "sa-sobol"             # data files base name (same as .lsd file)
varName   <- "U"                    # analysis variable name
nCnt      <- 1                      # country to use (0=all)
useStats  <- TRUE                   # add statistics to the set of variables
iniDrop   <- 100                    # initial time steps to drop (0=none)
nKeep     <- -1                     # number of time steps to keep (-1=all)
coresExp  <- 0                      # max cores for experiments (0=all)
savDat    <- FALSE                  # save data files and re-use if available?

# caption and file names
caption   <- "K+S Polynomial-Sool DoE analysis"# caption for logs
repName   <- ""                     # report files base name (if "" same as baseName)
datFilSfx <- "poly"                 # data file suffix

# aggregated variables and statistics to import and add
logVar    <- c( "A", "A1", "A2", "BadDeb", "Bon2", "C", "Creal", "Deb", "Deb1",
                "Deb2", "Def", "DefP", "EI", "G", "Gbail", "Gc", "Ged", "Gtrain",
                "M", "Mk", "Mc", "In", "Inom", "Ireal", "K", "Loans", "NWb",
                "NW1", "NW2", "Sav", "SavAcc", "S1", "S2", "Tax", "W1", "W2",
                "X", "Xk", "Xc", "Y", "Yreal", "dNnom" )
nlogVar   <- c( "CPI", "DebY", "DefPy", "F1", "F2", "L", "Ls", "L2", "Q2u",
                "TeAvg", "U", "Ue", "dCPI", "dY", "e", "entry1", "entry2",
                "entry1exit", "entry2exit", "exit1", "exit2", "f2posChg", "imi",
                "inn", "q2avg", "r", "sTavg", "sVavg" )
logStat   <- c( "A2preChg", "A2posChg", "CD", "CS", "TC", "wAvgReal",
                "wAvg1real", "wAvg2real", "wAvg3real", "w2realPreChg",
                "w2realPosChg" )
nlogStat  <- c( "A2sdPreChg", "A2sdPosChg", "Bda", "Bfail", "DefY", "Gini",
                "HH1", "HH2", "HP1", "HP2", "Lent", "Lexit", "Lpart", "U1",
                "U2", "U3", "V", "dA", "dw", "exit1fail", "exit2fail", "mu2avg",
                "q2preChg", "q2posChg", "V1", "V2", "V3", "wGini", "wLogSD" )
addVar    <- c( "Y_sd", "cris_llh", "freq_FE", "rec_dur", "rec_loss",
                "rec_num", "vu" )

# general flags
orderModel<- 0                      # polynomial model order (0=auto)
interactModel<- 0                   # use of interactive terms (0=auto/1=no/2=yes)
onlyCross <- FALSE                  # use only cross validation to select model
optimPar  <- FALSE                  # find optimized parameters (default: max/min)
krigingSA <- FALSE                  # use kriging specific SA algorithm
olsSignif <- 0.20                   # minimum significance considered in OLS regression
extWgth   <- 0.5                    # weight of external error on model selection (0-1)
conf      <- 0.95                   # confidence level to use
saSamples <- 1000                   # number of samples in sensitivity analysis

# force usage of specific factors in response surface graphs (0=auto)
factor1   <- 0                      # first factor (# according to DoE factor order)
factor2   <- 0                      # second factor
factor3   <- 0                      # third factor

# remove outliers from DoE & validation samples (use with care!)
remOutl   <- FALSE                  # remove outliers from DoE & validation samples?
limOutl   <- 10                     # limit deviation (number of standard deviations)

# parameters for variables creation and results evaluation
smoothing <- 1e5                    # HP filter smoothing factor (lambda)
crisisTh  <- -0.03                  # crisis growth threshold
crisisLen <- 3                      # crisis minimum duration (periods)
crisisPre <- 4                      # pre-crisis period to base trend start (>=1)

# report output configuration
raster    <- FALSE                  # raster or vector plots
res       <- 600                    # resolution of raster mode (in dpi)
plotRows  <- 1                      # number of plots per row in a page
plotCols  <- 1                      # number of plots per column in a page
plotW     <- 10                     # plot window width
plotH     <- 7                      # plot window height

# 3D surfaces visualization control
grid3d    <- 25                     # density for 3D wireframe plots
surf3d    <- FALSE                  # ask the user to adjust a 3D perspective
theta3d   <- 130                    # horizontal view angle
phi3d     <- 30                     # vertical view angle


# ==== Libraries, support functions and global options ====

source( "KS-support-functions.R" )  # load libraries and K+S support functions

set.seed( 1, kind = "default" )     # set the random number generator
options( warn = 0 )                 # -1=no warning/0:warnings at end/2:warnings stop
options( scipen = 5 )               # max 5 digits

# remove RStudio warnings for support functions
# !diagnostics suppress = textplot, log0, hpfilter, notIn, fmt, plot3d.morris
# !diagnostics suppress = rgl.snapshot, rgl.close, read.doe.lsd, model.pred.lsd
# !diagnostics suppress = sobol.decomposition.lsd, polynomial.model.lsd, persp3d
# !diagnostics suppress = response.surface.lsd, model.limits.lsd, model.optim.lsd
# !diagnostics suppress = showStartMark, showEndMark, catchError
# !diagnostics suppress = startTime, repFile, outDir, setCmdLinePars, saveCSV


# ==== Define function to create new variables ====

# function to evaluate the selected variables to 2D dataset (pool = TRUE)
eval.vars <- function( data, vars ) {

  if( length( notIn( vars, colnames( data ) ) ) > 0 )
    cat( "Missing variables in data:", notIn( vars, colnames( data ) ), "\n" )

  # ---- general variables ----
  tsteps <- nrow( data )

  # ---- recompute values for existing and create new variables ----

  for( var in vars ) {

    if( var %in% logVar ) {   # consider the log values of fast growing variables

      data[ , var ] <- log0( data[ , var ] )

    } else if( var == "Y_sd" ) {   # add the GDP std. dev. variable to data set

      data[ , var ] <- sd( data[ , "dY" ], na.rm = TRUE )

    } else if( var == "cris_llh" ) {   # add the crises likelihood variable to data set

      data[ , var ] <- sum( data[ , "dY" ] < -0.03, na.rm = TRUE ) /
                       sum( ! is.na( data[ , "dY" ] ) )

    } else if( var == "freq_FE" ) {   # add the frequency of crises variable to data set

      data[ , var ] <- sum( data[ , "U" ] == 0, na.rm = TRUE ) /
                       sum( ! is.na( data[ , "U" ] ) )

    } else if( var == "vu" ) {   # add the v/u (log detrended) variable to data set

      data[ , var ] <- log( data[ , "V" ] * data[ , "Ls" ] + 1 ) -
                       log( data[ , "U" ] * data[ , "Ls" ] + 1 )

    } else if( var == "rec_num" ) {   # add crisis recovery number, duration & losses

      # calculate long-term ex post growth rate trend
      growthTrend <- hpfilter( data[ , "dY" ], smoothing )$trend[ , 1 ]

      # Calculate recovery statistics for GDP to the pre-crisis trend
      recovery <- FALSE
      recTime <- recCost <- vector( mode = "numeric" )
      preCrisisY <- gTrend <- timeCrisis <- costCrisis <- NA
      for( i in 2 : tsteps ) {
        if( recovery ) {                                        # in a recovery?
          preCrisisY <- preCrisisY + gTrend                     # update pre crisis trend
          if( data[ i, "Yreal" ] >= preCrisisY ) {              # recovery is over?
            recovery <- FALSE
            if( i - timeCrisis > crisisLen ) { # record crisis longer than x periods
              recTime <- append( recTime, i - timeCrisis )
              recCost <- append( recCost, costCrisis )
            }
          } else {                                              # recovery not over
            gap <- preCrisisY - data[ i, "Yreal" ]              # update statistics
            costCrisis <- costCrisis + gap
          }
        }
        if( ! recovery && data[ i, "dY" ] < crisisTh && i > crisisPre ) {
          recovery <- TRUE
          timeCrisis <- i
          costCrisis <- 0
          preCrisisY <- mean( data[ ( i - crisisPre ) : ( i - 1 ), "Yreal" ] )
          gTrend <- mean( growthTrend[ ( i - crisisPre ) : ( i - 1 ) ], na.rm = TRUE )
        }
      }

      # consolidate results (same values for all time steps)
      if( length( recTime ) > 0 ) {
        data[ , "rec_num" ] <- length( recTime )
        data[ , "rec_dur" ] <- mean( recTime )
        data[ , "rec_loss" ] <- mean( recCost )
      } else {
        data[ , "rec_num" ] <- 0
        data[ , "rec_dur" ] <- 0
        data[ , "rec_loss" ] <- 0
      }
    }
  }

  return( data )
}


# ==== Process LSD result files ====

showStartMark( caption )    # log start mark

setCmdLinePars( sa = TRUE ) # read command line parameters (if any)

if( repName == "" )
  repName <- baseName

# include statistics to the variable set
if( useStats ) {
  logVar <- c( logVar, logStat )
  nlogVar <- c( nlogVar, nlogStat )
}

origVar <- c( logVar, nlogVar )

# make sure selected analysis variable is available
if( ! ( varName %in% origVar ) && ! ( varName %in% addVar ) )
  stop( "Invalid variable selected" )


# ---- Load result files ----

cat( "Reading DoE files...\n\n" )

if( nCnt == 0 ) posit <- NULL else posit <- paste0( "^", nCnt, "(_.+)?$" )
if( onlyCross ) doeNum <- 1 else doeNum <- 2

data <- read.doe.lsd( folder, baseName, varName, does = doeNum,
                      iniDrop = iniDrop, nKeep = nKeep, saveVars = origVar,
                      addVars = addVar, eval.vars = eval.vars, nnodes = coresExp,
                      posit = posit, posit.match = "regex", rm.outl = remOutl,
                      lim.outl = limOutl, rm.temp = ! savDat )


# ---- Select the best polynomial model ----

cat( "Estimating polynomial models...\n" )

model <- polynomial.model.lsd( data, ext.wgth = extWgth, ols.sig = olsSignif,
                               orderModel = orderModel,
                               interactModel = interactModel, digits = 3 )


# ---- Sensitivity analysis for best model ----

cat( "Calculating sensitivity analysis...\n\n" )

SA <- sobol.decomposition.lsd( data, model, sa.samp = saSamples )


# ---- Response surface 3D data for plotting ----

cat( "Modeling response surface...\n\n" )

defPos <- 2             # default settings position in plot set (1, 2 or 3)

response <- response.surface.lsd( data, model, SA, gridSz = grid3d,
                                  defPos = defPos, factor1 = factor1,
                                  factor2 = factor2, factor3 = factor3 )


# ---- Maximum and minimum responses for top factors ----

cat( "Finding response surface limits...\n\n" )

maxMin <- model.limits.lsd( data, model, SA )


# ====== Report generation ======

tryCatch( {   # enter error handling mode so PDF can be closed in case of error

  cat( "Generating reports...\n" )

  # create the report file(s) in a daily output directory
  repFile( repName, folder = folder, suffix = paste0( datFilSfx, "_", varName ),
           width = plotW, height = plotH, rows = plotRows, cols = plotCols,
           raster = raster, res = res )

  # ------ Model comparison/estimation tables ------

  textplot( fmt( model$comparison ), rmar = 1, cmar = 1.5 )
  title( main = "Comparison of alternative polynomial models",
         sub = "Q2: cross validation ( higher is better )\nRMSE/MAE/RMA: external validation RMSE/MAE/RMA ( lower is better )" )

  saveCSV( model$comparison, baseName = repName, baseFolder = folder,
           subFolder = outDir, suffix = datFilSfx,
           type = paste0( "model_", varName ) )

  textplot( model$estimation.std, show.colnames = FALSE, cmar = 2, rmar = 1 )
  title( main = "Polynomial meta-model estimation (standardized)",
         sub = paste0( "Variables rescaled to [0,1] / Average 95% CI = +/- ",
                       round( response$avgCIdev, digits = 2 ),
                       "\nPredicted output at defaults: ", varName, " = ",
                       round( response$default$mean, digits = 2 ),
                       ", 95% CI = [",
                       round( response$default$lower, digits = 2 ), ",",
                       round( response$default$upper, digits = 2 ),
                       "], time = [", iniDrop + 1, ",", nKeep, "]" ) )

  saveCSV( model$estimation.std, baseName = repName, baseFolder = folder,
           subFolder = outDir, suffix = datFilSfx,
           type = paste0( "estim_", varName ) )


  # ------ Sobol sensitivity analysis table/chart ------

  textplot( fmt( SA$sa, 3 ) )

  title( main = paste0( "Sobol decomposition indexes ( ", varName, " )" ),
         sub = paste0( " Samples = ", length( SA$metamodel$s ),
                       " / time = [", iniDrop + 1, ",", nKeep, "]" ) )

  barplot( t( SA$sa ), col = c( "white", "gray" ), las = 2, ylim = c( 0, 1 ),
           legend.text = c( "main effects", "interactions" ) )

  saveCSV( SA$sa, baseName = repName, baseFolder = folder,
           subFolder = outDir, suffix = datFilSfx,
           type = paste0( "sobol_", varName ) )

  title( main = paste0( "Sobol decomposition indexes ( ", varName, " )" ),
         sub = paste0( " Samples = ", length( SA$metamodel$s ),
                       " / time = [", iniDrop + 1, ",", nKeep, "]" ),
         ylab = "Sobol Index" )


  # ------ 2D response surface ------

  # plot 2D charts for top factors (around defaut parameter configuration)
  for( i in 1 : 3 ) {
    plot( response$grid[[ i ]], response$factor[[ i ]]$mean,
          ylim = c( min( response$calib[[ defPos ]]$lower ),
                    max( response$calib[[ defPos ]]$upper ) ),
          type = "l", xlab = colnames( data$doe )[ SA$topEffect[ i ] ],
          ylab = varName,
          main = paste0( "Meta-model response for parameter '",
                         colnames( data$doe )[ SA$topEffect[ i ] ], "'" ),
          sub = "Dotted lines at 95% confidence interval" )
    lines( response$grid[[ i ]], response$factor[[ i ]]$lower,
           col = "black", lty = 2 )
    lines( response$grid[[ i ]], response$factor[[ i ]]$upper,
           col = "black", lty = 2 )
    points( as.numeric( data$facDef[ SA$topEffect[ i ] ] ),
            response$default$mean,
            col = "red", pch = 19, cex = 2 )
    points( maxMin[ SA$topEffect[ i ], ( i * 2 ) - 1 ],
            maxMin[ "response", ( i * 2 ) - 1 ],
            col = "orange", pch = 18, cex = 2 )
    points( maxMin[ SA$topEffect[ i ], i * 2 ],
            maxMin[ "response", i * 2 ],
            col = "blue", pch = 18, cex = 2 )
  }


  # ------ 3D response surface (wireframe) ------

  if( SA$topEffect[ 1 ] > SA$topEffect[ 2 ] ) { # check if we have to swap x and y axis
    swapXY <- TRUE
  } else
    swapXY <- FALSE

  for( i in 1 : length( response$grid[[ 4 ]] ) ) {
    # plot 3D grid charts
    zMat <- matrix( response$calib[[ i ]]$mean, grid3d, grid3d, byrow = swapXY )

    #handle flat surfaces
    zlim <- range( zMat, na.rm = TRUE )
    if( zlim[ 1 ] == zlim[ 2 ] )
      if( zlim[ 1 ] != 0 ) {
        zlim <- zlim + c( - abs( zlim[ 1 ] ), abs( zlim[ 2 ] ) )
      } else
        zlim <- c( -1, 1 )

    vt <- persp( response$grid[[ 1 ]], response$grid[[ 2 ]], zMat, col = "gray90",
                 xlab = colnames( data$doe )[ SA$topEffect[ 1 ] ], zlim = zlim,
                 ylab = colnames( data$doe )[ SA$topEffect[ 2 ] ], zlab = varName,
                 theta = theta3d, phi = phi3d, ticktype = "detailed" )

    if( length( response$grid[[ 4 ]] ) == 1 ||
        ( length( response$grid[[ 4 ]] ) == 3 && i == 2 ) ) {
      points( trans3d( as.numeric( data$facDef[ SA$topEffect[ 1 ] ] ),
                       as.numeric( data$facDef[ SA$topEffect[ 2 ] ] ),
                       response$default$mean, vt ),
              col = "red", pch = 19, cex = 2 )
      points( trans3d( maxMin[ SA$topEffect[ 1 ], 7 ],
                       maxMin[ SA$topEffect[ 2 ], 7 ],
                       maxMin[ "response", 7 ], vt ),
              col = "orange", pch = 18, cex = 2 )
      points( trans3d( maxMin[ SA$topEffect[ 1 ], 8 ],
                       maxMin[ SA$topEffect[ 2 ], 8 ],
                       maxMin[ "response", 8 ], vt ),
              col = "blue", pch = 18, cex = 2 )
      subTitle <- paste0( "95% confidence interval: ", varName, " = [",
                          round( response$default$lower, 2 ),
                          ",", round( response$default$upper, 2 ),
                          "] at defaults (red dot)" )


      # ------ 3D response surface (shaded) ------

      if( surf3d ) {                                    # 3D GL model
        library( rgl, verbose = FALSE, quietly = TRUE )
        persp3d( response$grid[[ 1 ]], response$grid[[ 2 ]],
                 matrix( response$calib[[ i ]]$mean, grid3d, grid3d ),
                 col = "lightgray",
                 xlab = colnames( data$doe )[ SA$topEffect[ 1 ] ],
                 ylab = colnames( data$doe )[ SA$topEffect[ 2 ] ],
                 zlab = varName )
        readline( "Go to RGL window, resize it, adjust plot perspective, and press enter when done" )
        if( raster ) {
          rgl.snapshot( paste0( folder, "/", outDir, "/", baseName,
                                "_", datFilSfx, "_", varName,"_3d_%d.png" ) )
        } else {
          rgl.snapshot( paste0( folder, "/", outDir, "/", baseName,
                                "_", datFilSfx, "_3d_", varName, ".png" ) )
        }
        rgl.close( )
      }
    }
    else
      subTitle <- paste0( "All other parameters are at default settings" )

    title( main = paste( paste( "Meta-model response surface (",
                                colnames( data$doe )[ SA$topEffect[ 3 ] ],
                                "=", response$grid[[ 4 ]][ i ], ")" ) ),
           sub = subTitle )
  }


  # ------ 3D response surface (isolevels) ------

  for( i in 1 : length( response$grid[[ 4 ]] ) ) {
    zMat <- matrix( response$calib[[ i ]]$mean, grid3d, grid3d, byrow = swapXY )
    contour( response$grid[[ 1 ]], response$grid[[ 2 ]], zMat, nlevels = 12 )
    if( length( response$grid[[ 4 ]] ) == 1 ||
        ( length( response$grid[[ 4 ]] ) == 3 && i == 2 ) ) {
      points( data$facDef[ SA$topEffect[ 1 ] ], data$facDef[ SA$topEffect[ 2 ] ],
              col = "red", pch = 19, cex = 2 )
      points( maxMin[ SA$topEffect[ 1 ], 7 ],
              maxMin[ SA$topEffect[ 2 ], 7 ],
              col = "orange", pch = 18, cex = 2 )
      points( maxMin[ SA$topEffect[ 1 ], 8 ],
              maxMin[ SA$topEffect[ 2 ], 8 ],
              col = "blue", pch = 18, cex = 2 )
      subTitle <- paste0( "95% confidence interval: ", varName, " = [",
                          round( response$default$lower, 2 ),
                          ",", round( response$default$upper, 2 ),
                          "] at defaults (red dot)" )
    } else
      subTitle <- paste0( "All other parameters are at default settings" )

    title( main = paste( "Meta-model response surface (",
                         colnames( data$doe )[ SA$topEffect[ 3 ] ], "=",
                         response$grid[[ 4 ]][ i ], ")" ),
           sub = subTitle, xlab = colnames( data$doe )[ SA$topEffect[ 1 ] ],
           ylab = colnames( data$doe )[ SA$topEffect[ 2 ] ] )
  }


  # ====== Max/min of the polynomial meta-model parameters ======

  if( optimPar ) {

    for( k in c( TRUE, FALSE ) ) {           # minimize and maximize

      if( k ) label <- "minimizing" else label <- "maximizing"

      opt <- model.optim.lsd( model, data, minimize = k )

      if( is.na( opt[ 1 ] ) ) {
        textplot( paste( opt[1], "\n\nThe", label, "has failed!" ) )
        next
      }

      predOpt <- model.pred.lsd( opt, model )

      print <- fmt( t( opt ) )
      nRows <- length( print )
      maxRows <- 18
      if( nRows > maxRows ) {                # too many rows for a single column?
        nMove <- floor( nRows / 2 )
        col2.label <- names( print[ ( nRows - nMove + 1 ) : nRows, 1 ] )
        col2.value <- print[ ( nRows - nMove + 1 ) : nRows ]
        print <- print[ - ( ( nRows - nMove + 1 ) : nRows ), ]
        if( nMove < length( print ) ) {
          col2.label <- append( col2.label, "" )
          col2.value <- append( col2.value, "" )
        }
        print <- cbind( print, col2.label, col2.value )
      }

      textplot( print, show.colnames = FALSE )
      title( main = paste( "Settings for", label, "polynomial meta-model" ),
             sub = paste( "Predicted output at optimal setting:",
                          varName, "=", round( predOpt$mean, digits = 2 ) ) )

      cat( "\nParameter", label, ":\n" )
      cat( " Result:", varName, "=", predOpt$mean, "\n" )
      for( i in 1 : length( opt[ 1, ] ) )
        cat( " Parameter:", colnames( data$doe )[ i ], "=", opt[ 1, i ], "\n" )


      # ------ 3D response surface using max/min parameter values ------

      center2 <- list( )
      for( i in 1 : length( colnames( data$doe ) ) ) {
        if( i == SA$topEffect[ 1 ] )
          center2[[ i ]] <- response$grid[[ 1 ]]
        else
          if( i == SA$topEffect[ 2 ] )
            center2[[ i ]] <- response$grid[[ 2 ]]
          else
            center2[[ i ]] <- as.numeric( opt[ i ] )
      }

      pred2 <- model.pred.lsd( expand.grid( structure( center2,
                                                       .Names = colnames( data$doe ) ) ),
                               model )$mean

      zMat <- matrix( pred2, grid3d, grid3d, byrow = swapXY )

      #handle flat surfaces
      zlim <- range( zMat, na.rm = TRUE )
      if( zlim[ 1 ] == zlim[ 2 ] )
        if( zlim[ 1 ] != 0 ) {
          zlim <- zlim + c( - abs( zlim[ 1 ] ), abs( zlim[ 2 ] ) )
        } else
          zlim <- c( -1, 1 )

      vt2 <- persp( response$grid[[ 1 ]], response$grid[[ 2 ]], zMat,
                    col = "gray90", zlim = zlim, zlab = varName,
                    xlab = colnames( data$doe )[ SA$topEffect[ 1 ] ],
                    ylab = colnames( data$doe )[ SA$topEffect[ 2 ] ],
                    theta = theta3d, phi = phi3d, ticktype = "detailed"  )
      points( trans3d( as.numeric( opt[ SA$topEffect[ 1 ] ] ),
                       as.numeric( opt[ SA$topEffect[ 2 ] ] ),
                       predOpt$mean, vt2 ), col = "red", pch = 19, cex = 2 )
      title( main = paste( "Response surface for", label, "settings" ),
             sub = paste0( "95% confidence interval: ", varName, " = [",
                           round( predOpt$lower, 2 ), ",",
                           round( predOpt$upper, 2 ), "] at optimum (point)" ) )

      contour( response$grid[[ 1 ]], response$grid[[ 2 ]], zMat, nlevels = 12 )
      points( opt[ SA$topEffect[ 1 ] ], opt[ SA$topEffect[ 2 ] ],
              col = "red", pch = 19, cex = 2 )
      title( main = paste( "Response surface for", label, "settings" ),
             sub = paste0( "95% confidence interval: ", varName, " = [",
                           round( predOpt$lower, 2 ), ",",
                           round( predOpt$upper, 2 ), "] at optimum (point)" ),
             xlab = colnames( data$doe )[ SA$topEffect[ 1 ] ],
             ylab = colnames( data$doe )[ SA$topEffect[ 2 ] ] )
    }

    saveCSV( maxMin, baseName = repName, baseFolder = folder,
             subFolder = outDir, suffix = datFilSfx,
             type = paste0( "max-min_", varName ) )
  }


  # ------ End of report ------

}, interrupt = catchError, error = catchError, finally = showEndMark( ) )
