#*******************************************************************************
#
# --------------- Elementary Effects DoE analysis (Morris 1991) ---------------
#
#   Written by Marcelo C. Pereira, University of Campinas
#
#   Copyright Marcelo C. Pereira
#   Distributed under the GNU General Public License
#
#   The default configuration assumes that the supplied LSD
#   main simulation configuration (basename sa-ee):
#     R/data/sa-ee.lsd
#   is used with the also supplied sensitivity analysis (SA) set:
#     R/data/sa-ee.sa
#   to generate a set of configurations which must be executed
#   before this script is used
#
#   To generate the configuration set, (1) open LSD Model Manager
#   (LMM), (2) in LSD Model Browser, open the model which contains
#   this script (double click), (3) in LMM, compile and run the
#   model (menu Model>Compile and Run), (4) in LSD Model Browser,
#   load the desired configuration (menu File>Load), (5) load the
#   desired SA set (menu File>Load Sensitivity), (6) generate the
#   configuration set (menu Data>Sensitivity Analysis>EE Sampling),
#   accepting all the default options.
#
#   To execute the simulation set, (7) create a parallel processing
#   batch (menu Run>Parallel Batch), accepting to use the configura-
#   tion set just created and the default options, (8) execute the
#   created batch, accepting the option offered, (9) confirm opening
#   the background run monitor, (10) wait until all simulation runs
#   in the background run monitor finish.
#
#	  Several files are required to run this script:
#	  	folder/basename.lsd                       : LSD main configuration
#	  	folder/basename.sa                        : LSD SA set
#	  	folder/basename/basename_XX_YY.csv        : DoE specification
#	  	folder/basename/basename_XX_YY_WWW.res.gz : DoE response
#   The last two sets of files do NOT come with LSD and must be
#   generated by the steps described above before using this script.
#
#   IMPORTANT: this script assumes the R working directory is set
#   to the R subfolder where this script file is stored. This can
#   be done automatically in RStudio if a project is created at
#   this subfolder, or using the command setwd(). The "folder"
#   variable below must always point to a (relative) subfolder
#   of the R working directory.
#
#*******************************************************************************

# ====== User parameters ======

# database files / time steps to use
folder    <- "data"                 # data files folder
baseName  <- "sa-ee"                # data files base name (same as .lsd file)
varName   <- "U"                    # analysis variable name
nCnt      <- 0                      # country to use (0=all)
useStats  <- TRUE                   # add statistics to the set of variables
iniDrop   <- 200                    # initial time steps to drop (0=none)
nKeep     <- -1                     # number of time steps to keep (-1=all)
coresExp  <- 0                      # max cores for experiments (0=all)
savDat    <- FALSE                  # save data files and re-use if available?

# caption and file names
caption   <- "K+S EE DoE analysis"  # caption for logs
repName   <- ""                     # report files base name (if "" same as baseName)
datFilSfx <- "ee"                   # data file suffix

# aggregated variables and statistics to import and add
logVar    <- c( "A", "AcBas", "AcLux", "BadDeb", "BonC", "C", "CdBas", "CdLux",
                "Creal", "DcBas", "DcLux", "Deb", "Def", "EI", "Gbail", "Gcons",
                "Gtrain", "Gtrf", "GDPnom", "GDPreal", "I", "Inom", "Ireal",
                "Loans", "SavLux",  "Tax", "W", "dNnom", "kCavgBas", "kCavgLux" )
nlogVar   <- c( "CPI", "F1", "FcBas", "FcLux", "Ls", "PPI", "TeAvg", "U", "Ue",
                "dGDPreal", "entry1","exit1", "g1front", "g1max", "imi1",
                "inn1i", "inn1r", "sTavg", "sVavg" )
logStat   <- c( "AcPreChg", "AcPosChg", "Dc", "DebF", "In", "KcBas", "KcLux",
                "NW", "S", "TC", "VAcW", "Wc", "wAvgReal", "wCrealPosChg",
                "wCrealPreChg" )
nlogStat  <- c( "AsdCpreChg", "AsdCposChg", "Bda", "Bfail", "DebGDP", "DefGDP",
                "EXc", "EXk", "FcFbas", "FcFlux", "Gini", "HH1", "HHc", "HP1",
                "HPc", "LcBas", "LcLux", "Lent", "Lexit", "Lpart", "QcU", "V",
                "dA", "dCPI", "dw", "entryC", "exitC", "fCposChg", "muCavg",
                "muCavgBas", "muCavgLux", "qCavg", "qCposChg", "qCpreChg",
                "nCavg", "nCavgBas", "nCavgLux", "wGini", "wLogSD" )
addVar    <- c( "GDP_sd", "cris_llh", "freq_FE", "rec_dur", "rec_loss",
                "rec_num", "vu" )

# general flags
conf      <- 0.95                   # confidence level to use
p         <- 4                      # number of levels of the design
jump      <- 2                      # number of levels jumps when calculating EE

# remove outliers from DoE & validation samples (use with care!)
remOutl   <- FALSE                  # remove outliers from DoE & validation samples?
limOutl   <- 10                     # limit deviation (number of standard deviations)

# parameters for variables creation and results evaluation
smoothing <- 1e5                    # HP filter smoothing factor (lambda)
crisisTh  <- -0.03                  # crisis growth threshold
crisisLen <- 3                      # crisis minimum duration (periods)
crisisPre <- 4                      # pre-crisis period to base trend start (>=1)

# report output configuration
raster    <- FALSE                  # raster or vector plots
res       <- 600                    # resolution of raster mode (in dpi)
plotRows  <- 1                      # number of plots per row in a page
plotCols  <- 1                      # number of plots per column in a page
plotW     <- 10                     # plot window width
plotH     <- 7                      # plot window height

# 3D surfaces visualization control
surf3d    <- FALSE                  # ask the user to adjust a 3D perspective
theta3d   <- 130                    # horizontal view angle
phi3d     <- 30                     # vertical view angle


# ==== Libraries, support functions and global options ====

source( "KS-support-functions.R" )  # load libraries and K+S support functions

set.seed( 1, kind = "default" )     # set the random number generator
options( warn = 0 )                 # -1=no warning/0:warnings at end/2:warnings stop
options( scipen = 5 )               # max 5 digits

# remove RStudio warnings for support functions
# !diagnostics suppress = textplot, log0, hpfilter, notIn, fmt, plot3d.morris
# !diagnostics suppress = rgl.snapshot, rgl.close, read.doe.lsd
# !diagnostics suppress = elementary.effects.lsd, sobol.decomposition.lsd
# !diagnostics suppress = showStartMark, showEndMark, catchError
# !diagnostics suppress = startTime, repFile, outDir, setCmdLinePars, saveCSV


# ==== Define function to create new variables ====

# function to evaluate the selected variables to 2D dataset (pool = TRUE)
eval.vars <- function( data, vars ) {

  if( length( notIn( vars, colnames( data ) ) ) > 0 )
    cat( "Missing variables in data:", notIn( vars, colnames( data ) ), "\n" )

  # ---- general variables ----
  tsteps <- nrow( data )

  # ---- recompute values for existing and create new variables ----

  for( var in vars ) {

    if( var %in% logVar ) {   # consider the log values of fast growing variables

      data[ , var ] <- log0( data[ , var ] )

    } else if( var == "GDP_sd" ) {   # GDP std. dev.

      data[ , var ] <- sd( data[ , "dGDPreal" ], na.rm = TRUE )

    } else if( var == "cris_llh" ) {   # crises likelihood

      data[ , var ] <- sum( data[ , "dGDPreal" ] < -0.03, na.rm = TRUE ) /
                       sum( ! is.na( data[ , "dGDPreal" ] ) )

    } else if( var == "freq_FE" ) {   # frequency of crises

      data[ , var ] <- sum( data[ , "U" ] == 0, na.rm = TRUE ) /
                       sum( ! is.na( data[ , "U" ] ) )

    } else if( var == "vu" && useStats ) {   # V/U (log)

      data[ , var ] <- log( data[ , "V" ] * data[ , "Ls" ] + 1 ) -
                       log( data[ , "U" ] * data[ , "Ls" ] + 1 )

    } else if( var == "rec_num" ) {   # crisis recovery number, duration & losses

      # calculate long-term ex post growth rate trend
      growthTrend <- hpfilter( data[ , "dGDPreal" ], smoothing )$trend[ , 1 ]

      # Calculate recovery statistics for GDP to the pre-crisis trend
      recovery <- FALSE
      recTime <- recCost <- vector( mode = "numeric" )
      preCrisisGDP <- gTrend <- timeCrisis <- costCrisis <- NA
      for( i in 2 : tsteps ) {
        if( recovery ) {                                        # in a recovery?
          preCrisisGDP <- preCrisisGDP + gTrend                 # update pre crisis trend
          if( data[ i, "GDPreal" ] >= preCrisisGDP ) {          # recovery is over?
            recovery <- FALSE
            if( i - timeCrisis > crisisLen ) { # record crisis longer than x periods
              recTime <- append( recTime, i - timeCrisis )
              recCost <- append( recCost, costCrisis )
            }
          } else {                                              # recovery not over
            gap <- preCrisisGDP - data[ i, "GDPreal" ]          # update statistics
            costCrisis <- costCrisis + gap
          }
        }
        if( ! recovery && data[ i, "dGDPreal" ] < crisisTh && i > crisisPre ) {
          recovery <- TRUE
          timeCrisis <- i
          costCrisis <- 0
          preCrisisGDP <- mean( data[ ( i - crisisPre ) : ( i - 1 ), "GDPreal" ] )
          gTrend <- mean( growthTrend[ ( i - crisisPre ) : ( i - 1 ) ], na.rm = TRUE )
        }
      }

      # consolidate results (same values for all time steps)
      if( length( recTime ) > 0 ) {
        data[ , "rec_num" ] <- length( recTime )
        data[ , "rec_dur" ] <- mean( recTime )
        data[ , "rec_loss" ] <- mean( recCost )
      } else {
        data[ , "rec_num" ] <- 0
        data[ , "rec_dur" ] <- 0
        data[ , "rec_loss" ] <- 0
      }
    }
  }

  return( data )
}


# ==== Process LSD result files ====

showStartMark( caption )    # log start mark

setCmdLinePars( sa = TRUE ) # read command line parameters (if any)

if( repName == "" )
  repName <- baseName

# include statistics to the variable set
if( useStats ) {
  logVar <- c( logVar, logStat )
  nlogVar <- c( nlogVar, nlogStat )
}

origVar <- c( logVar, nlogVar )

# make sure selected analysis variable is available
if( ! ( varName %in% origVar ) && ! ( varName %in% addVar ) )
  stop( "Invalid variable selected" )

# ---- Load result files ----

cat( "Reading DoE files...\n\n" )

if( nCnt == 0 ) posit <- NULL else posit <- paste0( "^", nCnt, "(_.+)?$" )

data <- read.doe.lsd( folder, baseName, varName, iniDrop = iniDrop,
                      nKeep = nKeep, saveVars = origVar, addVars = addVar,
                      eval.vars = eval.vars, nnodes = coresExp, posit = posit,
                      posit.match = "regex", rm.outl = remOutl,
                      lim.outl = limOutl, rm.temp = ! savDat )


# ---- Elementary Effects analysis ----

cat( "Estimating Elementary Effects...\n" )

SA <- elementary.effects.lsd( data, p = p, jump = jump )


# ---- Sobol sensitivity analysis on experimental data ----

cat( "\nCalculating Sobol indexes...\n\n" )

sSA <- sobol.decomposition.lsd( data )


# ====== Report generation ======

tryCatch( {   # enter error handling mode so PDF can be closed in case of error

  cat( "Generating reports...\n" )

  # create the report file(s) in a daily output directory
  repFile( repName, folder = folder, suffix = paste0( datFilSfx, "_", varName ),
           width = plotW, height = plotH, rows = plotRows, cols = plotCols,
           raster = raster, res = res )

  # ------ Present sensitivity analysis for the EE model ------

  textplot( fmt( SA$table, 3 ) )
  title( main = paste0( "Elementary effects distributions statistics ( ",
                        varName, " )" ),
         sub = paste0( "Variables rescaled to [0,1] / H0: mu.star = 0\nLevels (p) = ",
                       p, ", delta = ", fmt( jump / ( p - 1 ) , 3 ),
                       ", trajectories (r) = ", SA$r,
                       ", samples = ", SA$samples,
                       ", time = [", iniDrop + 1, ",", nKeep, "]" ) )

  saveCSV( SA$table, baseName = repName, baseFolder = folder,
           subFolder = outDir, suffix = datFilSfx, type = varName )


  # ------ EE SA plots ------

  try( plot( SA ) )
  title( main = paste0( "Elementary effects composition ( ", varName, " )" ),
         sub = "mu.star: overall effects / sigma: non-linear/non-additive effects" )

  if( surf3d ) {                                    # 3D GL model
    require( rgl, warn.conflicts = FALSE, quietly = TRUE )
    plot3d.morris( SA )
    readline( "Go to RGL window, resize it, adjust plot perspective, and press enter when done" )

    if( raster ) {
      rgl.snapshot( paste0( folder, "/", outDir, "/", baseName, "_", datFilSfx,
                            "_3d_%d.png" ) )
    } else {
      rgl.snapshot( paste0( folder, "/", outDir, "/", baseName, "_", datFilSfx,
                            "_3d.png" ) )
    }

    rgl.close( )
  }


  # ------ Sobol sensitivity analysis table ------

  if( ! is.null( sSA ) ) {

    textplot( signif( sSA$sa, 3 ) )

    title( main = paste0( "Sobol decomposition indexes ( ", varName, " )" ),
           sub = paste0( "Variables rescaled to [0,1] / H0: mu.star = 0 / ",
                         "interaction effects are linear approximations\n",
                         "Levels (p) = ", p, ", delta = ", fmt( jump / ( p - 1 ) , 3 ),
                         ", trajectories (r) = ", SA$r, ", samples = ", SA$samples,
                         ", time = [", iniDrop + 1, ",", nKeep, "]" ) )

    barplot( t( sSA$sa ), col = c( "white", "gray" ), las = 2, ylim = c( 0, 1 ),
             legend.text = c( "main effects", "interactions" ) )

    title( main = paste0( "Sobol decomposition indexes ( ", varName, " )" ),
           sub = paste0( "Variables rescaled to [0,1] / H0: mu.star = 0 / ",
                         "interaction effects are linear approximations\n",
                         "Levels (p) = ", p, ", delta = ", fmt( jump / ( p - 1 ) , 3 ),
                         ", trajectories (r) = ", SA$r, ", samples = ", SA$samples,
                         ", time = [", iniDrop + 1, ",", nKeep, "]" ),
           ylab = "Sobol Index")

    saveCSV( sSA$sa, baseName = repName, baseFolder = folder,
             subFolder = outDir, suffix = datFilSfx,
             type = paste0( "sobol_", varName ) )

  } else
    textplot( "The B-spline modeling failed.\nSobol SA results are unavailable." )


  # ------ End of report ------

}, interrupt = catchError, error = catchError, finally = showEndMark( ) )
